services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bb-poc-app
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    configs:
      - poc_config

configs:
  poc_config:
    file: poc_link
