x-qwe: &d
  include:
    - oci://q1f75p-5-18-206-173.ru.tuna.am/poc/compose:latest

<<: *d

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    environment:
      - PORT=8080
